let money;
let income;
let addExpenses;
let deposit;
let mission;
let period;
alert("Привет мир!");
console.log("Пробная запись");
money = 80000;
income = 0;
addExpenses = "кредит, ЖКХ, интернет, бензин, продукты, телефон";
deposit = true;
mission = 1000000;
period = 12;
console.log('type money', typeof money);
console.log('type income', typeof income);
console.log('type deposit', typeof deposit);
console.log('длина addExpenses =', addExpenses.length);
console.log(`Период равен ${period} месяцев. Цель заработать ${mission} рублей`);
console.log(addExpenses.toLocaleLowerCase().split(', '));
const budgetDay = money / 30;
console.log('budgetDay: ', budgetDay);
